# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('game_description', models.CharField(max_length=1000)),
                ('game_mytype', models.CharField(max_length=40)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game_type')),
            ],
        ),
    ]
