# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cover',
            field=models.ImageField(default=2, upload_to='cover'),
            preserve_default=False,
        ),
    ]
