# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
